version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: golwin/foodgram_backend:latest
    volumes:
      - static:/app/static_django/
      - media:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: golwin/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  gateway:
    image: golwin/foodgram_nginx:latest
    ports:
      - 8000:80
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static_django
      - media:/media
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static:
  media: